modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MoriyaShiine/realistic-fire-spread/issues"
[[mods]]
modId="realisticfirespread"
version="${file.jarVersion}"
displayName="Realistic Fire Spread"
displayURL="https://www.curseforge.com/minecraft/mc-mods/realistic-fire-spread"
logoFile="icon.png"
authors="MoriyaShiine"
description='''Entities on fire will set fire to flammable blocks around them'''
[[dependencies.realisticfirespread]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.realisticfirespread]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
