modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (30 is current forge version)
issueTrackerURL="https://github.com/MoriyaShiine/realistic-fire-spread/issues" #optional
[[mods]] #mandatory
modId="realisticfirespread" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Realistic Fire Spread" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/realistic-fire-spread" #optional
authors="MoriyaShiine" #optional
description='''Entities on fire will set fire to flammable blocks around them.'''
[[dependencies.realisticfirespread]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.realisticfirespread]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"